import { useCallback, useEffect, useState } from 'react'

type Model = { name:string; installed:boolean; size?:number; quantization?:string; loaded:boolean; runtime_size?:number; context_length?:number; official:boolean; active:boolean; benchmark?:Record<string,unknown> }
type Inventory = { active_model:string; official_model:string; fallback_model:string; fallback_enabled:boolean; models:Model[] }

const mb=(value?:number)=>value?`${(value/1024/1024/1024).toFixed(2)} GB`:'—'

export function BrainLab(){
  const [data,setData]=useState<Inventory|null>(null); const [busy,setBusy]=useState(false); const [result,setResult]=useState<Record<string,unknown>|null>(null)
  const load=useCallback(()=>fetch('/api/brain/models').then(r=>r.json()).then(setData).catch(()=>setData(null)),[])
  useEffect(()=>{void load()},[load])
  const action=async(path:string,model:string,confirmed=false)=>{setBusy(true);try{const r=await fetch(`/api/brain/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,confirmed})});if(!r.ok)throw new Error((await r.json()).detail);setData(await r.json())}catch(e){alert(e instanceof Error?e.message:'Falha no Brain Lab')}finally{setBusy(false)}}
  const benchmark=async()=>{setBusy(true);try{const r=await fetch('/api/brain/benchmark',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({models:['qwen3:8b','qwen3.5:9b'],context_size:8192})});if(!r.ok)throw new Error((await r.json()).detail);const value=await r.json();setResult(value);await load()}catch(e){alert(e instanceof Error?e.message:'Benchmark falhou')}finally{setBusy(false)}}
  return <div className="settings-group brain-lab"><h3>AI · BRAIN LAB</h3><p>Oficial: <b>{data?.official_model??'—'}</b> · ativo: <b>{data?.active_model??'—'}</b> · fallback: {data?.fallback_model??'—'}</p><div className="brain-grid">{data?.models.map((model,index)=><article key={model.name} className={model.active?'selected':''}><strong>MODEL {index?'B':'A'} · {model.name}</strong><span>{model.installed?'INSTALLED':'NOT INSTALLED'} · {model.loaded?'LOADED':'UNLOADED'}</span><small>{mb(model.size)} · {model.quantization??'quantização não informada'} · ctx {model.context_length??8192}</small><div><button disabled={busy||!model.installed} onClick={()=>void action('use-temporarily',model.name)}>TEST {index?'B':'A'}</button><button disabled={busy||!model.installed} onClick={()=>{if(confirm(`Definir ${model.name} como cérebro oficial da NYRA?`))void action('select',model.name,true)}}>SET AS NYRA BRAIN</button></div></article>)}</div><div className="inline-actions"><button disabled={busy||!data?.models.every(m=>m.installed)} onClick={()=>void benchmark()}>{busy?'BENCHMARKING…':'COMPARE A/B'}</button><button disabled={busy} onClick={()=>void fetch('/api/brain/warmup',{method:'POST'}).then(r=>r.json()).then(setResult)}>WARM SELECTED</button><button disabled={busy} onClick={()=>void fetch('/api/brain/restore',{method:'POST'}).then(load)}>RESTORE OFFICIAL</button></div>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}<small>Nenhum benchmark altera automaticamente o cérebro oficial. Trocas frias podem levar minutos neste host.</small></div>
}
