import { useCallback, useEffect, useState } from 'react'

type BridgeState = 'DISABLED'|'DISCOVERING'|'FOUND'|'AUTH_REQUIRED'|'CONNECTING'|'CONNECTED'|'RECONNECTING'|'OFFLINE'|'AUTH_FAILED'|'INCOMPATIBLE'|'ERROR'
interface Settings { enabled:boolean;auto_discovery:boolean;discovery_interval:number;host:string;port:number;prefer_manual_host:boolean;voice_alerts:boolean;desktop_alerts:boolean;critical_only:boolean;store_event_history:boolean;create_episodic_memory:boolean;auto_reconnect:boolean;reconnect_backoff:number[];debug_mode:boolean;discovery_allowlist:string[];event_retention_days:number;alert_cooldown_seconds:number;disconnect_grace_seconds:number }
interface Status { state:BridgeState;host:string|null;sentinel_version:string|null;bridge_version:string;connected_since:string|null;last_event:{timestamp:string;title:string}|null;events_received:number;reconnect_count:number;token_configured:boolean;last_error:string }
interface EventRow { event_id:string;timestamp:string;severity:string;title:string;summary:string;entity:{name?:string} }
const DEFAULT:Settings={enabled:false,auto_discovery:true,discovery_interval:60,host:'',port:5000,prefer_manual_host:true,voice_alerts:true,desktop_alerts:true,critical_only:false,store_event_history:true,create_episodic_memory:false,auto_reconnect:true,reconnect_backoff:[1,2,5,10,30,60],debug_mode:false,discovery_allowlist:[],event_retention_days:30,alert_cooldown_seconds:300,disconnect_grace_seconds:7}

export function SentinelSettings(){
  const [settings,setSettings]=useState(DEFAULT);const[status,setStatus]=useState<Status|null>(null);const[events,setEvents]=useState<EventRow[]>([]);const[token,setToken]=useState('');const[notice,setNotice]=useState('');const[severity,setSeverity]=useState('')
  const load=useCallback(async()=>{const [a,b]=await Promise.all([fetch('/api/sentinel-watch/settings'),fetch(`/api/sentinel-watch/events?hours=24&limit=30&severity=${severity}`)]);if(a.ok){const value=await a.json();setSettings(value.settings);setStatus(value.status)}if(b.ok)setEvents((await b.json()).events)},[severity])
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer)},[load])
  const save=async(next=settings)=>{const response=await fetch('/api/sentinel-watch/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});setNotice(response.ok?(next.enabled?'Sentinel Watch ativado.':'Sentinel Watch desativado; discovery e stream encerrados.'):'Falha ao salvar a integração.');if(response.ok)setStatus(await response.json())}
  const toggle=(key:keyof Settings,value:boolean)=>{const next={...settings,[key]:value};setSettings(next);if(key==='enabled')void save(next)}
  const action=async(path:string,method='POST')=>{const response=await fetch(`/api/sentinel-watch/${path}`,{method});const value=await response.json().catch(()=>({}));setNotice(response.ok?(value.ok===false?'Sentinel não respondeu.':`Ação ${path} concluída.`):(value.detail??'Falha na ação.'));void load()}
  const saveToken=async()=>{const response=await fetch('/api/sentinel-watch/token',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});setNotice(response.ok?'Token salvo na área protegida local.':'Token inválido.');if(response.ok)setToken('');void load()}
  const simulate=async(level:string)=>{const response=await fetch('/api/sentinel-watch/debug',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({severity:level})});setNotice(response.ok?`Evento ${level} injetado somente na NYRA.`:'Ative Debug Mode para simular.');void load()}
  const openSentinel=()=>{if(status?.host)window.open(status.host,'_blank','noopener,noreferrer')}
  return <div className="settings-group sentinel-settings"><h3>INTEGRATIONS · UTAMO SENTINEL</h3><div className="sentinel-head"><strong className={`sentinel-state state-${(status?.state??'DISABLED').toLowerCase()}`}>{status?.state??'DISABLED'}</strong><span>Bridge v{status?.bridge_version??'1'} · Sentinel {status?.sentinel_version??'—'}</span></div>
    <div className="toggle-grid"><label><input type="checkbox" checked={settings.enabled} onChange={e=>toggle('enabled',e.target.checked)}/> Sentinel Watch</label><label><input type="checkbox" checked={settings.auto_discovery} onChange={e=>toggle('auto_discovery',e.target.checked)}/> Auto Discovery</label><label><input type="checkbox" checked={settings.voice_alerts} onChange={e=>toggle('voice_alerts',e.target.checked)}/> Voice Alerts</label><label><input type="checkbox" checked={settings.desktop_alerts} onChange={e=>toggle('desktop_alerts',e.target.checked)}/> Desktop Alerts</label><label><input type="checkbox" checked={settings.critical_only} onChange={e=>toggle('critical_only',e.target.checked)}/> Critical Only</label><label><input type="checkbox" checked={settings.auto_reconnect} onChange={e=>toggle('auto_reconnect',e.target.checked)}/> Auto Reconnect</label><label><input type="checkbox" checked={settings.store_event_history} onChange={e=>toggle('store_event_history',e.target.checked)}/> Store History</label><label><input type="checkbox" checked={settings.create_episodic_memory} onChange={e=>toggle('create_episodic_memory',e.target.checked)}/> Episodic Memory</label><label><input type="checkbox" checked={settings.debug_mode} onChange={e=>toggle('debug_mode',e.target.checked)}/> Debug Mode</label></div>
    <div className="settings-grid"><label>SENTINEL HOST<input value={settings.host} onChange={e=>setSettings({...settings,host:e.target.value})} placeholder="127.0.0.1 ou host da LAN"/></label><label>PORT<input type="number" value={settings.port} onChange={e=>setSettings({...settings,port:Number(e.target.value)})}/></label><label>DISCOVERY INTERVAL<input type="number" value={settings.discovery_interval} onChange={e=>setSettings({...settings,discovery_interval:Number(e.target.value)})}/></label><label>ALLOWLIST LAN<input value={settings.discovery_allowlist.join(',')} onChange={e=>setSettings({...settings,discovery_allowlist:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})} placeholder="192.168.1.0/24"/></label><label>VOICE COOLDOWN<input type="number" value={settings.alert_cooldown_seconds} onChange={e=>setSettings({...settings,alert_cooldown_seconds:Number(e.target.value)})}/></label><label>RETENTION DAYS<input type="number" value={settings.event_retention_days} onChange={e=>setSettings({...settings,event_retention_days:Number(e.target.value)})}/></label></div>
    <div className="sentinel-token"><label>BRIDGE TOKEN<input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder={status?.token_configured?'Configurado · informe apenas para substituir':'Cole o token gerado no Sentinel'}/></label><button disabled={token.length<32} onClick={()=>void saveToken()}>SALVAR TOKEN</button><small>O token vai apenas ao backend local e não é retornado à interface.</small></div>
    <div className="settings-actions"><button onClick={()=>void save()}>SALVAR</button><button onClick={()=>void action('discover')}>PROCURAR AGORA</button><button onClick={()=>void action('reconnect')}>CONECTAR</button><button onClick={()=>void action('disconnect')}>DESCONECTAR</button><button onClick={()=>void action('test','GET')}>TESTAR</button><button disabled={!status?.host} onClick={openSentinel}>ABRIR SENTINEL</button><button onClick={()=>void action('saved-host','DELETE')}>LIMPAR HOST</button></div>
    {settings.debug_mode&&<div className="settings-actions"><button onClick={()=>void simulate('info')}>SIMULAR INFO</button><button onClick={()=>void simulate('warning')}>SIMULAR WARNING</button><button onClick={()=>void simulate('critical')}>SIMULAR CRITICAL</button><button onClick={()=>void simulate('recovery')}>SIMULAR RECOVERY</button></div>}
    <div className="sentinel-metrics"><span>Host <b>{status?.host??'—'}</b></span><span>Eventos <b>{status?.events_received??0}</b></span><span>Reconnects <b>{status?.reconnect_count??0}</b></span><span>Último <b>{status?.last_event?new Date(status.last_event.timestamp).toLocaleTimeString('pt-BR'):'—'}</b></span></div>
    <div className="sentinel-events"><header><strong>RECENT SENTINEL EVENTS</strong><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All</option><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option><option value="recovery">Recovery</option></select></header>{events.length===0?<p>Nenhum evento recebido.</p>:events.map(event=><article key={event.event_id} className={`severity-${event.severity}`}><time>{new Date(event.timestamp).toLocaleString('pt-BR')}</time><strong>{event.title}</strong><span>{event.entity?.name||event.summary}</span></article>)}</div>
    {status?.last_error&&<p className="lab-notice">{status.last_error}</p>}{notice&&<p className="lab-notice">{notice}</p>}
  </div>
}
