head_x: [FaceAngleX, ParamAngleX]
head_y: [FaceAngleY, ParamAngleY]
head_tilt: [FaceAngleZ, ParamAngleZ]
eye_x: [EyeBallX, ParamEyeBallX, EyeLeftX, EyeRightX]
eye_y: [EyeBallY, ParamEyeBallY, EyeLeftY, EyeRightY]
mouth_open: [MouthOpen, VoiceVolumePlusMouthOpen, ParamMouthOpenY]
mouth_form: [MouthSmile, ParamMouthForm]
body_x: [BodyAngleX, ParamBodyAngleX]
breathing: [ParamBreath]
neural_link: [KazumiNeuralLink, ParamKazumiNeuralLink]
attention: [KazumiAttention, ParamKazumiAttention]
thinking: [KazumiThinking, ParamKazumiThinking]
concern: [KazumiConcern, ParamKazumiConcern]
amused: [KazumiAmused, ParamKazumiAmused]
