from __future__ import annotations

from .models import CandidateScores, CandidateStatus, VoiceCandidate


def _scores(*values: float) -> CandidateScores:
    return CandidateScores.model_validate(dict(zip(CandidateScores.model_fields, values, strict=True)))


def curated_candidates() -> list[VoiceCandidate]:
    """License-reviewed catalog. Descriptions never substitute the linked primary source."""
    raw = [
        dict(
            id="omnivoice-brpt-calm-design", name="OmniVoice BR-PT · Calm Design",
            source="edwixx/omnivoice-brpt-v15 + k2-fsa/OmniVoice",
            source_url="https://huggingface.co/edwixx/omnivoice-brpt-v15", type="Synthetic",
            gender="Female (designed)",
            license="Apache-2.0", license_url="https://github.com/k2-fsa/OmniVoice/blob/master/LICENSE",
            allowed_use="Voz sintética criada por voice design, sem áudio de pessoa; uso, derivação e redistribuição sob Apache-2.0.",
            reference_allowed=True, redistributable=True, commercial_use=True,
            identity_terms="Proibido usar o modelo para personificação ou clonagem sem consentimento.",
            size_bytes=2450344144, provider="omnivoice_brpt", provider_voice="female-young-low-calm",
            location="LOCAL", naturalness_estimate=8.2, integration_difficulty="HIGH",
            status=CandidateStatus.SAFE_FOR_KAZUMI_REFERENCE,
            scores=_scores(9.3, 8.8, 8.2, 8.5, 8.0, 4.8, 8.4, 9.4, 5.8), top_candidate=True,
            notes=["Experimental em pt-BR; voice design é mais estável em inglês/chinês segundo o projeto.", "Checkpoint de 2,45 GB; CPU Windows é viável para triagem, não para baixa latência."],
        ),
        dict(
            id="kokoro-kazumi-voice-v2", name="Kokoro · KAZUMI Feminina V2",
            source="hexgrad/Kokoro-82M + kokoro-onnx", source_url="https://huggingface.co/hexgrad/Kokoro-82M",
            type="Synthetic", license="Apache-2.0", license_url="https://huggingface.co/hexgrad/Kokoro-82M",
            allowed_use="TTS local direto com embedding sintético estável composto de vozes do pacote Apache-2.0.",
            reference_allowed=False, redistributable=False, commercial_use=True,
            identity_terms="Identidade sintética própria da KAZUMI; não representa nem imita uma pessoa real.", size_bytes=326000000,
            provider="kokoro", provider_voice="kazumi_voice_v2", location="LOCAL", naturalness_estimate=7.8,
            integration_difficulty="LOW", status=CandidateStatus.SAFE_FOR_DIRECT_TTS,
            scores=_scores(8.9, 8.6, 7.8, 7.6, 7.4, 7.8, 8.9, 9.2, 9.8), top_candidate=True,
            notes=["Embedding 85% af_heart + 15% pf_dora; tokenizer pt-BR.", "A/B obrigatório preservado em .tmp/voice-change-v2."],
        ),
        dict(
            id="kokoro-pf-dora", name="Kokoro · Dora",
            source="hexgrad/Kokoro-82M + kokoro-onnx", source_url="https://huggingface.co/hexgrad/Kokoro-82M",
            type="Synthetic", license="Apache-2.0", license_url="https://huggingface.co/hexgrad/Kokoro-82M",
            allowed_use="TTS local direto com pesos Apache-2.0; não usar a saída como clone permanente sem revisão adicional.",
            reference_allowed=False, redistributable=False, commercial_use=True,
            identity_terms="Voz sintética empacotada; prioridade para uso direto.", size_bytes=326000000,
            provider="kokoro", provider_voice="pf_dora", location="LOCAL", naturalness_estimate=7.3,
            integration_difficulty="LOW", status=CandidateStatus.SAFE_FOR_DIRECT_TTS,
            scores=_scores(8.7, 8.4, 7.3, 7.2, 7.1, 7.8, 8.9, 9.2, 9.8), top_candidate=True,
            notes=["Única voz portuguesa feminina do pacote atual; já funcional como fallback."],
        ),
        dict(
            id="chatterbox-multilingual-default", name="Chatterbox Multilingual · Default",
            source="ResembleAI/chatterbox", source_url="https://huggingface.co/ResembleAI/chatterbox",
            type="Synthetic", gender="Synthetic female sample", license="MIT", license_url="https://github.com/resemble-ai/chatterbox/blob/master/LICENSE",
            allowed_use="TTS local direto com modelo oficial MIT; sem referência de terceiros.",
            reference_allowed=False, redistributable=False, commercial_use=True,
            identity_terms="Watermark neural Perth; não personificar pessoas.", size_bytes=3900000000,
            provider="chatterbox_multilingual_v3", provider_voice="default", location="LOCAL",
            naturalness_estimate=8.0, integration_difficulty="MEDIUM", status=CandidateStatus.SAFE_FOR_DIRECT_TTS,
            scores=_scores(8.3, 7.8, 7.0, 7.7, 7.0, 4.2, 8.1, 9.1, 6.2), top_candidate=True,
            notes=["Modelo já instalado e worker residente; CPU é lento neste host.", "O benchmark real teve baixa inteligibilidade técnica; a nota foi reduzida após STT."],
        ),
        dict(
            id="edge-thalita-multilingual", name="Microsoft · Thalita Multilingual",
            source="Microsoft Edge Read Aloud", source_url="https://learn.microsoft.com/azure/ai-services/speech-service/language-support",
            type="TTS Provider", license="Microsoft service terms (Edge endpoint)",
            license_url="https://www.microsoft.com/servicesagreement",
            allowed_use="Audição pessoal pelo provider; o endpoint Edge não concede licença explícita para redistribuição ou clonagem.",
            reference_allowed=False, redistributable=False, commercial_use=None,
            identity_terms="Não reutilizar como referência biométrica; Azure pago possui termos separados.",
            provider="edge_tts", provider_voice="pt-BR-ThalitaMultilingualNeural", location="ONLINE",
            naturalness_estimate=8.6, integration_difficulty="LOW", status=CandidateStatus.AUDITION_ONLY,
            scores=_scores(9.7, 9.2, 8.6, 7.2, 8.1, 8.8, 9.2, 3.5, 9.2), top_candidate=True,
            notes=["Disponibilidade confirmada no catálogo real do host em 2026-08-19."],
        ),
        dict(
            id="edge-francisca", name="Microsoft · Francisca",
            source="Microsoft Edge Read Aloud", source_url="https://learn.microsoft.com/azure/ai-services/speech-service/language-support",
            type="TTS Provider", license="Microsoft service terms (Edge endpoint)",
            license_url="https://www.microsoft.com/servicesagreement",
            allowed_use="Audição pessoal pelo provider; sem licença explícita para clonagem ou redistribuição.",
            reference_allowed=False, redistributable=False, commercial_use=None,
            identity_terms="Não reutilizar como referência biométrica.", provider="edge_tts",
            provider_voice="pt-BR-FranciscaNeural", location="ONLINE", naturalness_estimate=8.3,
            integration_difficulty="LOW", status=CandidateStatus.AUDITION_ONLY,
            scores=_scores(9.8, 9.3, 8.3, 7.4, 7.8, 8.9, 9.2, 3.5, 9.2),
            notes=["Disponibilidade confirmada no catálogo real do host em 2026-08-19."],
        ),
        dict(
            id="azure-luana-mai", name="Azure Speech · Luana MAI Voice 2",
            source="Microsoft Azure Speech", source_url="https://learn.microsoft.com/azure/ai-services/speech-service/language-support",
            type="TTS Provider", license="Microsoft Product Terms · paid tier",
            license_url="https://www.microsoft.com/licensing/terms/productoffering/MicrosoftAzure/MCA",
            allowed_use="TTS direto via Azure pago; direitos de saída dependem do paid tier e dos Product Terms.",
            reference_allowed=False, redistributable=False, commercial_use=True,
            identity_terms="Não disponível pelo endpoint gratuito Edge; credencial e cobrança obrigatórias.",
            provider="azure_speech", provider_voice="pt-BR-Luana:MAI-Voice-2", location="PAID_OPTION",
            naturalness_estimate=9.1, integration_difficulty="MEDIUM", status=CandidateStatus.SAFE_FOR_DIRECT_TTS,
            scores=_scores(9.8, 9.4, 9.1, 8.6, 9.0, 9.1, 9.5, 8.2, 5.5), top_candidate=True,
            notes=["Não integrada nem comprada; catálogo oficial atual confirma pt-BR feminina e estilos."],
        ),
        dict(
            id="azure-manuela", name="Azure Speech · Manuela Neural",
            source="Microsoft Azure Speech", source_url="https://learn.microsoft.com/azure/ai-services/speech-service/language-support",
            type="TTS Provider", license="Microsoft Product Terms · paid tier",
            license_url="https://www.microsoft.com/licensing/terms/productoffering/MicrosoftAzure/MCA",
            allowed_use="TTS direto via Azure pago; sem clonagem.", reference_allowed=False,
            redistributable=False, commercial_use=True, provider="azure_speech",
            provider_voice="pt-BR-ManuelaNeural", location="PAID_OPTION", naturalness_estimate=8.6,
            integration_difficulty="MEDIUM", status=CandidateStatus.SAFE_FOR_DIRECT_TTS,
            scores=_scores(9.8, 9.3, 8.6, 8.0, 8.5, 8.8, 9.4, 8.2, 5.5),
            notes=["Catálogo oficial; requer assinatura/credencial, não ativada."],
        ),
        dict(
            id="google-neural2-a", name="Google Cloud · Neural2-A",
            source="Google Cloud Text-to-Speech", source_url="https://cloud.google.com/text-to-speech/docs/voices",
            type="TTS Provider", license="Google Cloud Terms (paid service)",
            license_url="https://cloud.google.com/terms/service-terms",
            allowed_use="TTS direto via Google Cloud com credencial e cobrança; sem clonagem.",
            reference_allowed=False, redistributable=False, commercial_use=True, provider="google_cloud_tts",
            provider_voice="pt-BR-Neural2-A", location="PAID_OPTION", naturalness_estimate=8.4,
            integration_difficulty="MEDIUM", status=CandidateStatus.SAFE_FOR_DIRECT_TTS,
            scores=_scores(9.8, 9.1, 8.4, 7.5, 8.1, 8.7, 9.3, 7.8, 5.0),
            notes=["Não integrada nem comprada."],
        ),
        dict(
            id="f5-tts-ptbr", name="F5-TTS PT-BR · firstpixel/fuuuzzy",
            source="firstpixel/F5-TTS-pt-br", source_url="https://huggingface.co/firstpixel/F5-TTS-pt-br",
            type="Model", gender="Reference-dependent", license="CC-BY-NC-4.0", license_url="https://creativecommons.org/licenses/by-nc/4.0/",
            allowed_use="Pesquisa e audição não comercial; referência de voz externa continua exigindo consentimento.",
            reference_allowed=False, redistributable=True, commercial_use=False,
            identity_terms="Dataset e identidade da referência não oferecem base suficiente para uma voz permanente.",
            size_bytes=1348431976, provider="f5_tts_ptbr", location="LOCAL", naturalness_estimate=8.4,
            integration_difficulty="HIGH", status=CandidateStatus.AUDITION_ONLY,
            scores=_scores(9.1, 5.0, 8.4, 7.5, 8.1, 8.0, 8.0, 4.5, 3.0),
            notes=["Não baixado: licença não comercial, referência obrigatória e dependências pesadas."],
        ),
        dict(
            id="common-voice-ptbr-female", name="Mozilla Common Voice · speaker individual",
            source="Mozilla Common Voice", source_url="https://commonvoice.mozilla.org/datasets",
            type="Dataset", gender="Metadata-dependent", license="CC0 dataset + Common Voice Terms",
            license_url="https://commonvoice.mozilla.org/terms",
            allowed_use="Pesquisa/audição de corpus; não converter uma pessoa contribuinte em identidade permanente da KAZUMI.",
            reference_allowed=False, redistributable=True, commercial_use=None,
            identity_terms="Não tentar reidentificar, contatar ou personificar contribuidores.", provider="dataset",
            location="ONLINE", naturalness_estimate=8.0, integration_difficulty="HIGH",
            status=CandidateStatus.AUDITION_ONLY, scores=_scores(9.5, 7.0, 8.0, 6.5, 8.0, 8.0, 6.5, 3.0, 2.5),
            notes=["Nenhum áudio individual foi baixado."],
        ),
        dict(
            id="piper-ptbr-current", name="Piper pt-BR · catálogo atual",
            source="rhasspy/piper-voices", source_url="https://huggingface.co/rhasspy/piper-voices/tree/main/pt/pt_BR",
            type="Model", gender="Not documented", license="Per-voice MODEL_CARD", license_url="https://github.com/rhasspy/piper/blob/master/VOICES.md",
            allowed_use="Uso direto depende da licença de cada voz; o catálogo primário não documenta uma candidata feminina que atenda ao requisito.", reference_allowed=False,
            redistributable=False, commercial_use=None, provider="piper", location="LOCAL",
            naturalness_estimate=6.5, integration_difficulty="LOW", status=CandidateStatus.REJECTED,
            scores=_scores(9.0, 0.0, 6.5, 5.0, 5.5, 7.0, 8.0, 5.0, 8.5),
            notes=["cadu, edresson, faber e jeff existem no catálogo, mas o gênero não é documentado pela fonte primária; nenhuma voz foi inferida pelo nome."],
        ),
        dict(
            id="qwen3-tts-voice-design", name="Qwen3-TTS · VoiceDesign 1.7B",
            source="QwenLM/Qwen3-TTS", source_url="https://github.com/QwenLM/Qwen3-TTS",
            type="Synthetic", gender="Female (designed)", license="Apache-2.0", license_url="https://github.com/QwenLM/Qwen3-TTS/blob/main/LICENSE",
            allowed_use="Voice design sintético sob Apache-2.0; não depende de áudio de uma pessoa como referência.",
            reference_allowed=True, redistributable=True, commercial_use=True, provider="qwen3_tts_voice_design",
            provider_voice="female-young-adult-calm-low", location="LOCAL", naturalness_estimate=8.5,
            integration_difficulty="HIGH", status=CandidateStatus.SAFE_FOR_KAZUMI_REFERENCE,
            scores=_scores(6.5, 8.5, 8.5, 8.2, 8.3, 7.0, 8.5, 9.4, 3.0),
            notes=["O projeto oficial declara Portuguese, não pt-BR nativo.", "Não baixado: 1,7B, hardware AMD/CPU e orçamento total já consumido tornariam esta triagem desproporcional."],
        ),
    ]
    candidates = [VoiceCandidate.model_validate(item) for item in raw]
    for candidate in candidates:
        candidate.refresh_score()
    return candidates
